### ISSUE TITLE
Too many files error downgrading JP N3DS to 9.2.0

### ISSUE THREAD

**Issue by Myriachan** [Plailect/sysDowngrader#11]
I tried running sysDowngrader on my Japanese N3DS running 9.9.0-26J in order to downgrade to 9.2.0-20J using the guide's 9.2.0-20J(Full)_n3DS.zip, but I get this error message:

if(filesDirs.size() > regionVersionMap.second.size()) throw titleException(_FILE_, **LINE**, res, "Too many titles in /updates/ found!\n");

**Comment by Myriachan** [comment]
SHA256 of the file = 01FFD6D75602A40BE1EFBA4B5397AAE660FF5EF6C97A14A41EFB9DEAAFC9ADA3

This is weird, because it doesn't match what issue #6 says.

**Comment by Plailect** [comment]
Fixed.
