### ISSUE TITLE
[Enhancement]sysDowngrader should remove Menuhax

### ISSUE THREAD

**Issue by gnmmarechal** [Plailect/sysDowngrader#13]
If the user used MenuHax, this will always result in a black screen after the downgrade (due to Menuhax not being set up for the correct version). Imo, sysDowngrader should auto-remove the relevant files from the SD after finishing the downgrade.

**Comment by Plailect** [comment]
This would be out of scope for the project, it can be used for things other than just the guide.

**Comment by gnmmarechal** [comment]
I suppose so, it makes sense.
