### ISSUE TITLE
N3DS XL Won't boot - Failed downgrade - error: titleException: title.cpp: 126: Result: 0xC920181A

### ISSUE THREAD

**Issue by Armen1er** [Plailect/sysDowngrader#14]
Hi,

Can someone please help me? I have a N3DS USA and I was on 10.3-28U (I think 28U not sure). I followed the guide and when I used the sysdowngrader to 9.2.0 I received an error "error: titleException: title.cpp: 126: Result: 0xC920181A
![20160918_222854](https://cloud.githubusercontent.com/assets/22286395/18623014/b3a68b22-7e05-11e6-9c64-9c2bb98f5238.jpg)
"

Now the 3DS blue light goes on but the screens are black/off and after a few seconds the blue led goes off. I tried to do step 10 and tried without the sd card and tried removing the battery for a few seconds.

Does anyone have any suggestions or alternatives to fix this? I can't seem to find this error code anywhere either :(

I attached a screenshot of the error.

**Comment by Plailect** [comment]
The file `0004013020001602.cia` is the New 3DS camera application. (see [here](https://www.3dbrew.org/wiki/Title_list#00040130_-_System_Modules))

I have never seen the error 0xC920181A, but it has the following description:    

```
Module: OS (6) | Description: Session closed by remote (os) (26) | Summary: Canceled (9) | Level: Status (25)
```

You'll want to attempt to boot [Recovery Mode](https://www.3dbrew.org/wiki/Recovery_Mode), however be aware that this will update you to 11.1.0-34.

**Comment by Armen1er** [comment]
Thanks for the swift response! I was lucky enough to upgrade to 11. I was going to have hardmod installed either way in case of BSOD in the future so I'm shipping it out today. 

Thanks for the guide!
