### ISSUE TITLE
It doesn't do checks if you're using the wrong region unlike PlaiSysupdater

### ISSUE THREAD

**Issue by akirayuki** [Plailect/sysDowngrader#15]
As stated above, it doesn't do checks/error out when flashing the wrong region. As far as I remember, when I used PlaiSysupdater, I kept getting a nintendo error after a couple of validations. It turns out that I am using the wrong region, so when i replaced the update files to the correct one, it went thru with the downgrade. I almost thought I bricked my new device when I flashed a 9.2 US console on my EUR console. It doesn't boot up, only blue led and that's it. Good thing recovery mode works so I update to the latest firmware. Good thing I have a spare CFW'ed EUR console to dsiwarehaxx downgrade.

**Comment by Plailect** [comment]
https://github.com/Plailect/sysDowngrader/commit/7a7a15944a861107f2bbd0b10727818bc00e4d9b
