### ISSUE TITLE
Cannot Get AM:U handle

### ISSUE THREAD

**Issue by kurrptsenate** [Plailect/sysDowngrader#16]
went from 11.1 to 10.4 with Field Runners downgrade.  Everything passed in the 3DResident Check.  I enter the HBL from OoT.  When running sysDowngrader, it hangs on the AM:U handle check.  I've tried this 50+ times.  I entered HBL with Mario Sticker Star but had the same effect

**Comment by Plailect** [comment]
Did you check your kernel version with 3DSident like you were told?
