### ISSUE TITLE
SysDowngrader deleted the first CIA, then, "File not found"

### ISSUE THREAD

**Issue by CesarSP99** [Plailect/sysDowngrader#18]
I've done A9LH on four 3DS's using Plailect's guide, three New 3DS and one Old 3DS, but in the 4th N3DS, I don't know why SysDowngrader failed, it made the hash checks successfully, but then, when the downgrade process started, as you now, first, it uninstall the system title and then install the CIA from the updates folder, but in the first CIA (I think it's mset) failed with a "File not found" error, it stuck, so First I pressed back trying to get HB launcher, got red screen and then black screen, nothing more, so I shut down the 3DS holding power button and now always I try to boot it up I get "An error has occurred..." Error. I can't access neither recovery nor touch calibration.

**Comment by Plailect** [comment]
If you can reproduce this with a [log](https://github.com/Plailect/sysDowngrader/commit/59739cc42c3c4d9fc9624e62e885c933e9fdc827), feel free to reopen.
