### ISSUE TITLE
Problem to downgrade a hardmodded console

### ISSUE THREAD

**Issue by ph1signals** [Plailect/sysDowngrader#2]
Hello,

The problem appear on a hardmodded console, (injecting the NATIV FIRM 10.4)

It's impossible to start the dowgrade to 9.2.0. This message appears "Did not get am:u handle !"
The HBL is started by browserhax or menuhax.

The most recently Starter pack has been used and the format of console tryed

**Comment by kloklojul** [comment]
just poweroff the console and retry unitll it works

**Comment by ph1signals** [comment]
I poweroff the console several times.
