### ISSUE TITLE
Downgrade not going through

### ISSUE THREAD

**Issue by generalan** [Plailect/sysDowngrader#21]
So I am going through your guide and I am using sysDowngrader. Whenever I enter and choose downgrade, it just says
"checking for am:u... 
Did not get am:u handle!

Attempting svchax..."

**Comment by generalan** [comment]
Okay, so I got that part working.

Now when it says I got the am:u handle, on the bottom it says 
"Hash mismatch! File is corrupt or i correct! 

Please reboot."

**Comment by james-d-elliott** [comment]
Hash mismatch sounds like wrong files in the updates folder, delete it and make sure you have the correct ones.
