### ISSUE TITLE
Update file? 

### ISSUE THREAD

**Issue by Marika4Princess** [Plailect/sysDowngrader#22]
I downloaded the zip, but I see no ''update'' file.... I still tried to downgrade and it says the update file is missing... what is wrong? thx for helping me out..

**Comment by james-d-elliott** [comment]
Sounds like you're on the guide? If you're on this step: https://plailect.github.io/Guide/9.2.0-downgrade

then you find the updates folder inside the zip file that starts with 9.2.0 and matches your console. For example if you have the EUR console and it's a N3DS the zip will be called 9.2.0-20E(Full)_n3DS.zip - see the section that says "The 9.2.0 downgrade pack zip file for your device and region:" **YOU MUST get the correct archive for your console, so be careful and read carefully.**

sysDowngrader is the tool that downgrades, it doesn't have the downgrade files (updates folder).

**Comment by Marika4Princess** [comment]
I downloaded the right zip, but it is only a file. I cannot open it so I do not see any file. Am I supposed to use this file? Or is it supposed to be a folder? Please have a look. I use the old 3ds from United States (Canada actually)

**Comment by Plailect** [comment]
https://github.com/Plailect/sysDowngrader/blob/master/README.md#instructions

**Comment by Marika4Princess** [comment]
Okay so tell me if I got this right : I created a ''updates'' folder on the root of my SD card. Then I've transfer the 9.2.0-20U torrent in it. And then I downgrade. Right? So that's what I did but seems like I didn't downgrade yet. Thank you for you time again.

**Comment by james-d-elliott** [comment]
If you mean transferred the contents of the zip (from the torrent download) then yes. There should be a whole heap of files with long names the same length. There are about 120-140 from memory. They end in CIA. If you don't have those files, you need to open the torrent with a BitTorrent client.

**Comment by Marika4Princess** [comment]
Okay so I downloaded the client. I transfered the updates file. I did the downgrade, it rebooted ''after 10 seconds'' and now it stays on the black screen. When I reboot it it still shows me the black screen. Hm... Can't get onto Homebrew menu either.

**Comment by Marika4Princess** [comment]
Nevermind, I got it !! I deleted the file for US, but it wasnt on the emplacement it showed in the guide. Thank you for your patience guys!
