### ISSUE TITLE
homebrew stopped working

### ISSUE THREAD

**Issue by Marika4Princess** [Plailect/sysDowngrader#23]
Hi guys, 
I successfully downgraded my 3ds to version 9.2, but now my homebrew isn't launching anymore... Any leads? I want to install A9LH.

**Comment by james-d-elliott** [comment]
You probably have the wrong ropbin if you're using browserhax. . Please follow this again:

https://3ds.guide/homebrew-launcher-(browser)

Menuhax will not work (holding a key on bootup), if you're using another entry point make sure all the otherapp files are correct and follow the guide the hax author provides. They are listed on this page: 
https://3ds.guide/homebrew-launcher-(no-browser)

**Comment by Marika4Princess** [comment]
That worked perfectly thank you ! Do you have any guide I can trust to install arm9loaderhax ? This is what I need to do so I need to install it: https://3ds.guide/dsiware-downgrade

**Comment by james-d-elliott** [comment]
That is the most trustworthy guide I know of. At the end of the downgrade you just have to follow the path that is relevant to you. If you need more help you should join #3dshacks on Rizon IRC.
