### ISSUE TITLE
"Too many titles in /updates/ found!" when downgrading to 9.2.0

### ISSUE THREAD

**Issue by OussamaDanba** [Plailect/sysDowngrader#3]
When trying to downgrade to 9.2.0 from 9.9.0 using sysUpdater instead of PlaiSysUpdater (which worked fine) I'm encountering a "Too many titles in /updates/ found!" error. Looking through a few reddit posts about the guide being updated it seems I am not alone in this regard. The checksum is correct fwiw.

A few reddit posts being confirming they have the same issue:
https://www.reddit.com/r/3dshacks/comments/4z9cbv/full_arm9loaderhax_cfw_guide_update_now_supports/d6vxcvv
https://www.reddit.com/r/3dshacks/comments/4z9cbv/full_arm9loaderhax_cfw_guide_update_now_supports/d6vu8rs
https://www.reddit.com/r/3dshacks/comments/4zapqb/3dshacking_qa_nitro_sd_cards_edition/d6vctgx

**Comment by kloklojul** [comment]
i second this. Downgrade didn't work with the same error on a GER n3DSXL on 11.0.0 with DSi method already applied.

**Comment by iuzwpr2p39rh7w** [comment]
The error seems to lie in sysDowngrader's hash maps.
I only have `9.2.0-20E(Full).zip` and `9.2.0-20E(Full)_n3DS.zip` available at the moment so I could only test them.
While `9.2.0-20E(Full).zip`'s hashes are correct, `9.2.0-20E(Full)_n3DS.zip`'s hash [map](https://github.com/Plailect/sysDowngrader/blob/master/include/hashes.h#L757) is [not](https://gist.github.com/iuzwpr2p39rh7w/838ccc1ddcfe0f75678f9b68048b64c1).
The correct SHA-256 checksums are [here](https://gist.github.com/iuzwpr2p39rh7w/573a7981f4d31bac0672509db6641deb).

**Comment by Plailect** [comment]
Fixed with latest commit
