### ISSUE TITLE
SysDowngrader says wrong file?

### ISSUE THREAD

**Issue by SebastianDCH** [Plailect/sysDowngrader#30]
Hey up everybody. 

So i tryed to use the "new" Version boot get prompted wirh the following message:

> titleException:
main.cpp:241: Result: 0x0
[31mFirmware files are not for this device region!

[sysDowngrader.zip](https://github.com/Plailect/sysDowngrader/files/668765/sysDowngrader.zip)

So am i supposed to use the old version? 

The update files are definitly right. 

Greetings Seb

**Comment by Plailect** [comment]
https://github.com/Plailect/sysDowngrader/commit/d96dbac5715422e7d47e56d0585ad6df2b1f3587
