### ISSUE TITLE
homebrew launching

### ISSUE THREAD

**Issue by Marika4Princess** [Plailect/sysDowngrader#31]
I used my game pokemon sapphire to transfer my homebrew on my new3ds. (basehax) 
Now that I am on version 9.2.0 though, my homebrew isnt launching from pokemon anymore. So I used this guide to be able to use it again https://3ds.guide/homebrew-launcher-(browser) , but after the process when I try to start up homebrew while booting my n3ds, the top screen just becomes grey and the bottom stays black. Like it wants to start but doesnt. Any lead ? 

Ty.

**Comment by Plailect** [comment]
This is a *hax issue on your end.
