### ISSUE TITLE
"Too few titles in /updates/ found!" When downgrading to 9.1.0-20J (N3DS)

### ISSUE THREAD

**Issue by FrozenChen** [Plailect/sysDowngrader#6]
It seems there is more problems with hash, this time with the 9.1.0-20J update pack for japanese n3ds

SHA-256=9BA7BC4EEAB39B484E710D7AD05BFEAE3B143812D85BBE128F283A79AA1BA80B

Sysdowngrader shows the message "Too few titles in /updates/ found!" and refuses to downgrade the system, downgrading with the same pack with plaisysupdater works.

[Proof](http://imgur.com/a/XbLsl) (by /u/Davex220 on reddit)

This was tested on a japanese n3ds 9.9.0-26J

**Comment by Plailect** [comment]
https://github.com/Plailect/sysDowngrader/commit/8c8b1bba74ca264bd97e3f046666e4bdf4977eae

**Comment by Myriachan** [comment]
Now it says too many.  https://github.com/Plailect/sysDowngrader/issues/11
