### ISSUE TITLE
"Too few titles in /updates/ found!" When downgrading to 9.2.0-20U (N3DS)

### ISSUE THREAD

**Issue by ieatchoy** [Plailect/sysDowngrader#7]
I'm getting the above error when trying to downgrade N3DS 10.7.0-32U to 9.2.0-20U.

I'm using sysDowngrader 1.0.3.

I've seen similar issues reported for J and E versions related to the hash map in sysDowngrader.  Could this be the same issue?

**Comment by Plailect** [comment]
You are probably missing some of the files then, I just checked and the hash map is correct.

**Comment by ieatchoy** [comment]
Figured out that the issue had to deal with hidden files.  Thanks
