### ISSUE TITLE
Sysdowngrader 9.7.0-25j problem

### ISSUE THREAD

**Issue by jasontwk85** [Plailect/sysDowngrader#8]
Hi.. i got a question.
At sysdowngrader step.. at the end it suppose to downgrade from my original (9.7.0-25j) to 9.2.0-20j.. 
But after i done and i check at setting (3ds home menu) is writen my version is 9.1.0-20j..
Is it i do wrong step? Or is it normal after downgrade? 
Or should i just continue the process?
I afraid if wrong ver. After downgrade will cause brick..

Thanks.
And sorry for inconvenience cause.

**Comment by jasontwk85** [comment]
And i.m using n3ds..

Thanks,
And appreciate.

**Comment by ihaveamac** [comment]
9.1 is about the same anyway, don't worry about it.

**Comment by jasontwk85** [comment]
Ok,thanks..
I will continue the following step..👍
