### ISSUE TITLE
Wrong error when trying O3DS 9.2.0 pack on N3DS

### ISSUE THREAD

**Issue by Myriachan** [Plailect/sysDowngrader#9]
If you try to downgrade to Old 3DS 9.2.0 on a New 3DS, it correctly fails, but gives you the wrong error message.

if(ciaFileInfo.titleID == 0x0004013800000002LL && is_n3ds != 0)
throw titleException(_FILE_, **LINE**, res, "Installing N3DS pack on O3DS will always brick!");

**Comment by Plailect** [comment]
Fixed.
